### ISSUE TITLE
Crash when using an id that doesn't exist in the repository

### ISSUE THREAD

**Issue by Jip-Hop** [php-tmdb/api#103]
`$repository = new \Tmdb\Repository\TvRepository($tmdb_client);
$entry = $repository->load(298312);`

`Fatal error: Uncaught exception 'Tmdb\Exception\TmdbApiException' with message 'The resource you requested could not be found.' in /vendor/php-tmdb/api/lib/Tmdb/HttpClient/`

Same for the movie repository with a high id:

`$repository = new \Tmdb\Repository\MovieRepository($tmdb_client);
$entry = $repository->load(298312000);`

`Fatal error: Uncaught exception 'Tmdb\Exception\TmdbApiException' with message 'The resource you requested could not be found.' in /vendor/php-tmdb/api/lib/Tmdb/HttpClient/`

Is this the way it should be? I'm currently using a try/catch block to prevent crashes.

**Comment by DeeJaVu** [comment]
yes that's the way it is, when a ID does not exist it returns a api status code 34 https://www.themoviedb.org/documentation/api/status-codes

**Comment by Jip-Hop** [comment]
Maybe nicer to just return an empty object instead of throwing an error which crashes the program if not handled accordingly. It's not obvious or documented that php-tmdb throws an error in this scenario.

**Comment by wtfzdotnet** [comment]
I strongly disagree returning an empty object. This would make detecting errors and handling them appropriately nearly impossible.

However more specific errors would be welcome, that all extend the same api exception or an other logical parent of the error, so backwards compatibility is kept. These errors are thrown because of the response that tmdb returns, which is an actual error response.

**Comment by wtfzdotnet** [comment]
I rather think the way you are trying to catch the error is faulty, probably because you are not importing the namespace for the exceptions, and thus it isn't catched.

**Comment by Jip-Hop** [comment]
All right so it is a well considered design choice then. Is there an example on github on how to gracefully handle errors in case I load a movie by the tmdb id which no longer exists (which is a scenario in which this error is thrown)?

**Comment by wtfzdotnet** [comment]
See https://github.com/php-tmdb/api/blob/2.0/examples/exception_handling.php

**Comment by AdhaarSharma** [comment]
We can use Try and Exception to get an empty object which will work as a placeholder. I was facing the same issue during data fetch for a machine learning project and it fixed it for me.
