### ISSUE TITLE
Update symfony/event-dispatcher dependency to version 3

### ISSUE THREAD

**Issue by MarkRedeman** [php-tmdb/api#105]
([See](https://github.com/php-tmdb/laravel/issues/23))
Upgrading the `symfony/event-dispatcher` version of [TMDB/Laravel](https://github.com/php-tmdb/laravel) to version `~3.0` requires TMDB/API to also upgrade its dependency to version three.

The unit tests seem to be passing when I upgrade the dependency to version 3, though since I'm not actively using this package I'm not sure if there are any issues with upgrading.

**Comment by wtfzdotnet** [comment]
@MarkRedeman I'll dig into it tomorrow, have to catch up with changes to the TMDB API anyway. Thanks for the input on the issues at the laravel side :+1:

**Comment by wtfzdotnet** [comment]
This was resolved with recent changes from @rkip
