### ISSUE TITLE
Headers informations

### ISSUE THREAD

**Issue by florentsorel** [php-tmdb/api#107]
Hi,

I need more info about X-RateLimit-Reset timestamp. I have a timestamp 1450861077 but it's a past date (12/23/2015 à 9:57:57) the time is already past.

How to reset the limitation? Because I each every page in discover TV API to save the informations in DB.

By the way, I don't understand why after 2 requests my limit is 39 and not 38. Can you explain the limit please ? In the [TMDB FAQ](https://www.themoviedb.org/faq/api): 30 requests every 10 seconds (I suppose is 40 now due to header information) so my requests are executed in less than 10 seconds. Why 39 and not 38 ?

```php
$query = new DiscoverTvQuery();
$data = $this->repository->discoverTv($query);
$popular = $this->movies->getPopular();

$response = $this->repository->getClient()->getHttpClient()->getLastResponse()->getHeaders()->get('X-RateLimit-Remaining')[0];
dump($response); // 39
```

**Comment by wtfzdotnet** [comment]
My guess is you are looking at a cached response ( for both the timestamp and the count, thus that's why it is still 39 instead of 38 ), if you are building up a local collection you will have to adhere to the rules of TMDB. While looping over several movies that are not cached I'd assume you will see different results.

**Comment by Rtransat** [comment]
Indeed, it was cached. I will sleep 10 seconds after 39/40 requests if I don't use cache ;).

Yes if I build a local collection I see the rules (I guess ?). It need to display a TMDB logo ? Can you paste the page about that just in case ?

**Comment by wtfzdotnet** [comment]
You can replace the cache with a different implementation, if you wish ( and I'd recommend doing so as the default uses the file system for caching ).

All concerns about TMDB itself, take a look here https://www.themoviedb.org/documentation/api/terms-of-use
