### ISSUE TITLE
TvSeasonRepository::load Bug

### ISSUE THREAD

**Issue by BlackGh0st** [php-tmdb/api#116]
There's a issue when loading a TV-Season with the TvSeasonRepository.

The problem is, while I'm passing an instance of a tv season, the repo. takes the id of the season instead of the season number. 

There's also a issue with the null check on line 52, this should by typesave. PHP casts a season 0 (for pilos or special seasons) to null

https://github.com/php-tmdb/api/blob/2.1-beta/lib/Tmdb/Repository/TvSeasonRepository.php#L49
https://github.com/php-tmdb/api/blob/2.1-beta/lib/Tmdb/Repository/TvSeasonRepository.php#L52

**Comment by wtfzdotnet** [comment]
Thanks, sorry for the late merge :o
