### ISSUE TITLE
Search API: URLs are encoded twice

### ISSUE THREAD

**Issue by nbraquart** [php-tmdb/api#121]
Hello,

I spotted an issue with the search API. It seems that the URLs are encoded two times:

1. On TMDB API side, before delegating the request to the HTTP adapter;
2. On Guzzle side, before actually sending the HTTP request.

This is not a big issue in most cases, "Breaking Bad" becomes "Breaking+Bad" and then "Breaking%2BBad", but TMDB still recognizes it. However, for special characters like accents, it completely prevents TMDB from returning a response.

Nicolas

**Comment by wtfzdotnet** [comment]
Fix has been merged, releasing 2.1 soon
