### ISSUE TITLE
Clearcache parameter

### ISSUE THREAD

**Issue by migburillo** [php-tmdb/api#122]
Hey!

What about adding a clearcache parameter to force the invalidation of current request cache?
I'm trying to find out how to do it but no luck yet

Thanks!

**Comment by wtfzdotnet** [comment]
Because of the various allowed options for caching from 2.1 onwards I'm not exactly sure what the best method would be ( other than interfacing a lot away ... ).

Depending on your application I'd suggest you inject a cache handler yourself, which you can clear.

**Comment by wtfzdotnet** [comment]
Going to close this issue, as I'd consider this resolved, if you do have any questions though about registering your own handler do reach out!

**Comment by migburillo** [comment]
ok, thanks!! I'll try it

**Comment by wtfzdotnet** [comment]
If you need some help I'm in the office now anyway, add me at michael at wtfz.net on hangouts
