### ISSUE TITLE
MovieRepository Genres 

### ISSUE THREAD

**Issue by DeeJaVu** [php-tmdb/api#123]
Is there a way to get Genres with MovieRepository $movies->getPopular() method ? it only returns the id for genres, 

for now i have created a `movie_genres` table with `genre_id`,`genre_name `columns like below

| id 	| genre_id 	| name 	|
|----	|----------	|-----------------	|
| 2 	| 12 	| Adventure 	|
| 3 	| 16 	| Animation 	|
| 4 	| 35 	| Comedy 	|
| 5 	| 80 	| Crime 	|
| 6 	| 99 	| Documentary 	|
| 7 	| 18 	| Drama 	|
| 8 	| 10751 	| Family 	|
| 9 	| 14 	| Fantasy 	|
| 10 	| 36 	| History 	|
| 11 	| 27 	| Horror 	|
| 12 	| 10402 	| Music 	|
| 13 	| 9648 	| Mystery 	|
| 14 	| 10749 	| Romance 	|
| 15 	| 878 	| Science Fiction 	|
| 16 	| 10770 	| TV Movie 	|
| 17 	| 53 	| Thriller 	|
| 18 	| 10752 	| War 	|
| 19 	| 37 	| Western 	|

now in Laravel i can do

```blade
@foreach ($popular as $movie)
    @foreach($movie->getGenres() as $genres)
        @foreach(\DB::table('movie_genres')->where('genre_id', $genres->getId())->pluck('name') as $genre)
            {{ $genre }}
        @endforeach
    @endforeach
@endforeach
```

this works but i find this ugly is there a smarter way to retrieve the genre names ?

**Comment by wtfzdotnet** [comment]
I'd suggest because TMDB does not return `genres` as a parameter to cache these genres in say for example Redis, in your ( Controller? Not familiar with laravel ). Then I would simply populate the genres before I return the data to the template at all.

To give you a little hint, you can always use the `setGenres` function of an movie/tv object. I think a better solution would be to register an `EventListener` to the hydration system. _However_, this currently is not possible because I have never taken the context into account from where you are hydrating objects.

Moving forward to the new API version I'd guess if the need is still there for a context to be given this will be implemented differently.

**Comment by DeeJaVu** [comment]
ok thanks, i have on more question instead of opening a new issue i will ask it here
i am using TvSearchQuery for my autocomplete search, and for the searchType() you can specify a search type.. on the docs it says `For those wanting more of an "autocomplete" type search, set this option to 'ngram'.` i have tested both `ngram`, and `phrase`, but i have seen no difference !

what are the difference between ngram and phrase ?

**Comment by travisbell** [comment]
Hi @DeeJaVu

Are you seeing some docs with the reference to ngram/phrase? I removed references to those parameters months ago, and they haven't been valid for close to a year. All searches are ngram now, if you want autocomplete just send your partial search.

**Comment by DeeJaVu** [comment]
@travisbell Hello master, i meand the docs here https://github.com/php-tmdb/api/blob/2.1/lib/Tmdb/Model/Search/SearchQuery/TvSearchQuery.php#L64

**Comment by travisbell** [comment]
Ok, cool. Then it's @wtfzdotnet's problem ;) I just wanted to make sure you weren't mentioning something from our docs because then it would be my problem 😆

**Comment by wtfzdotnet** [comment]
Looks I missed the note about those being removed, I'll adjust the methods later tonight. ;) @travisbell I added you on hangouts, can we have a short talk about v4 of the API? Cheers

**Comment by travisbell** [comment]
@wtfzdotnet I'm around for the next ~5 hours if you ping me.

**Comment by wtfzdotnet** [comment]
@travisbell you've got mail :-)

@DeeJaVu Seeing the parameter became obsolete I'll check the code for references and remove them as such.

**Comment by wtfzdotnet** [comment]
@DeeJaVu deprecated in 2.1.3 with 7a4b0ae7eff14176c9d5c1b9c8d6a389beea3c64

**Comment by Fatih90** [comment]
@wtfzdotnet @DeeJaVu i made a helper function to retrieve the genre names for movies, i am using laravel

```php
<?php

use Tmdb;

function getMovieGenreName($id)
{
    $list = Tmdb::getGenresApi()->getMovieGenres();

    if (isset($list['genres'])) {
        foreach ($list['genres'] as $g) {
            if (intval($g['id']) === intval($id)) {
                return $g['name'];
            }
        }
    }

    return null;
}
```

now i can use it liek this
 
```blade
<span class="genres">
    @foreach($popular->getGenres() as $genre)
    {{ getMovieGenreName($genre->getId()) }}{{ $loop->remaining ? ',' : '' }}
    @endforeach
</span>
```
