### ISSUE TITLE
Missing gender from Person Model

### ISSUE THREAD

**Issue by geochatz** [php-tmdb/api#124]
It seems that the setGender() and getGender() methods are missing from the Person model.

**Comment by wtfzdotnet** [comment]
Available in 2.1.4, please do send merge requests!

**Comment by Fatih90** [comment]
@wtfzdotnet i am using `"php-tmdb/laravel": "^1.1",`
and using dependency injection for Tmdb\Repository\PeopleRepository
i dont see the getGender() method !

![download](https://user-images.githubusercontent.com/22959827/30406061-a891dc0e-98ef-11e7-9662-43d583b718f7.png)

**Comment by yukoff** [comment]
@Fatih90 First of all, thanks for your PR (#37), but it won't fix the issue you've described - please check out [this comment](https://github.com/php-tmdb/laravel/pull/37#issuecomment-329355163) for details.
