### ISSUE TITLE
Episode guest_stars collection is not returned 

### ISSUE THREAD

**Issue by geochatz** [php-tmdb/api#126]
For each TV Episode there is  a Guest Star array that is not returned by the Episodes->getCredits() function.

It seems that the guest star class is missing so when the api returns that collection the json_decode function cannot find an appropriate class to cast it. 

_**Steps to reproduce:**_
Execute the getCredits() function in the Episodes repository and pass the following parameters
tv_id = 1402
season_number = 1
episode_number = 5

The collection does not have a guest_stars collection.

If you execute the same query to the Movie DB api (https://developers.themoviedb.org/3/tv-episodes/get-tv-episode-credits) you will see that there is a guest_stars collection of credits

**Comment by wtfzdotnet** [comment]
Fixed in 2.1.5 :) thanks for the details!

**Comment by wtfzdotnet** [comment]
Managed to push this onto the wrong main branch *arg*

**Comment by wtfzdotnet** [comment]
@geochatz reverted the 2.0 commit, and cherry picked it into 2.1, dinner time! :)
