### ISSUE TITLE
how to search in other language?

### ISSUE THREAD

**Issue by DevMakoto** [php-tmdb/api#134]
how to search in other language? is possible? example "es-ES"

**Comment by y68** [comment]
@DevMakoto maybe `https://api.themoviedb.org/3/movie/550?api_key={api_key}&language=es-ES` ?

**Comment by okaufmann** [comment]
Just append ?language=es-ES to the search query, as stated in the official documentation:
https://developers.themoviedb.org/3/search/search-movies

To do this with the API Client create a MovieSearchQuery, set the language and pass it to the search method:

```php
$token  = new \Tmdb\ApiToken('your_tmdb_api_key_here');
$client = new \Tmdb\Client($token);

$searchRepo = new \Tmdb\Repository\SearchRepository($client);

$searchQuery = new MovieSearchQuery();
$searchQuery->language("es-ES");
$result = $searchRepo->searchMovie("Rouge One", $searchQuery);

```

You could set the language globally either:

https://github.com/php-tmdb/api#plug-ins-1

**Comment by wtfzdotnet** [comment]
Thanks @okaufmann, I intentionally didn't respond because this is documented ( if this needs improvement hit me with a banana ), appreciate your effort helping out :)

**Comment by okaufmann** [comment]
@wtfzdotnet I was able to told the solution out of my mind an just typed it in 😉. Like to something back to this awesome and very useful package as well.

Is the MovieSearchQuery-thing nowhere documented or am I blind?

**Comment by DevMakoto** [comment]
thanks! okaufmann
