### ISSUE TITLE
ImageHelper doesn't serve secure images

### ISSUE THREAD

**Issue by rdgout** [php-tmdb/api#138]
I noticed that the ImageHelper uses a function getUrl().

Unfortunately, this always serves the `$config['base_url']`
When using this URL on a secure website, you get issues with mixed content. Is there a special reason the function always defaults to the non-secure version?

Seems to me it would be better served to just serve from the secure version always, there is no downside.

**Comment by wtfzdotnet** [comment]
I vaguely remember changing this to remove the protocol specification completely and depend on the protocol being used. I'll check this in a bit :)

**Comment by wtfzdotnet** [comment]
Resolved in 66290094bccc0ecc0f6020ecac3965829a9dccea
