### ISSUE TITLE
Getting credits

### ISSUE THREAD

**Issue by jerauf** [php-tmdb/api#140]
I don't see anywhere in the documentation how to retrieve credits.

Can that be done?

**Comment by wtfzdotnet** [comment]
Have you browsed through the examples ?

**Comment by wtfzdotnet** [comment]
@jerauf did you find what you were looking for in the examples?

**Comment by jerauf** [comment]
Yes.

**Comment by wtfzdotnet** [comment]
Ok @jerauf if you have any more questions you know where to find me :)
