### ISSUE TITLE
Secure option does nothing

### ISSUE THREAD

**Issue by gooverdian** [php-tmdb/api#145]
$client = new \Tmdb\Client($token, ['secure' => false]);
    $search = $api_client->getSearchApi()->searchMulti($query);
That code is still making https request. It seems, that in HttpClient.php `constructSecureUrl($path)` function uses https explicitly.

Further exploration suggests changing function body to
`return $this->options['base_url'] . $path;`
because `secure` option is already handled in Client.php `postResolve` function assigning `options['base_url']` right url with http protocol, when `'secure' => false`.

**Comment by yukoff** [comment]
@gooverdian, This issue has been fixed in #149, fix will be included in `v2.1.10`. For now you can use `php-tmdb/api=^2.1@dev`.
