### ISSUE TITLE
Consider replacing Guzzle with httplug

### ISSUE THREAD

**Issue by greg0ire** [php-tmdb/api#151]
This library requires Guzzle 6, which means it cannot be installed on applications that use Guzzle 5 if I'm correct. Using http://httplug.io/ would make that issue go away.

**Comment by yukoff** [comment]
So what is the problem updating guzzle to version 6?

**Comment by greg0ire** [comment]
To me, none, I'm starting a new project. But other people might be stuck because they use libraries not compatible with guzzle 6 yet.

**Comment by yukoff** [comment]
Could you be more specific - what libraries, which incompatibilities you are referring to? Both guzzle6 and httplug use [PSR-7](http://www.php-fig.org/psr/psr-7/) for HTTP messages, so I don't see any point to replace one with another.

**Comment by greg0ire** [comment]
Httplug is an abstraction over guzzle, or buzz, or curl, or whatever library the user chooses to use in a project. It avoids installing many libraries, and can avoid conflicts with libraries which, just like yours, make use of an http client. I am on my phone, so it's hard to find specific examples right now, sorry.

**Comment by Nyholm** [comment]
Here is a list of advantages to use the HTTPlug abstraction:

- **End user choice**: The end user will have the choice of the http client implementation, which will be, for a majority of user, the [guzzle6 library](http://docs.php-http.org/en/latest/clients/guzzle6-adapter.html). However some others librairies can be chosen, like [Zend/Http](https://github.com/php-http/zend-adapter) or [CakePHP](https://github.com/php-http/cakephp-adapter) one which are already available in their respective framework.
  
  By not couple us to Guzzle6 we allow people to use this library with Guzzle5 (or [any other adapter](http://docs.php-http.org/en/latest/clients.html)).
- **Less maintenance on this library**: HTTPlug offer a large feature set [(with the usage of the client-common package)](http://docs.php-http.org/en/latest/components/client-common.html) which does not need to be rewrite in this library: Retry failed requests, Load Balancing (Client Pool), Failure detection, logging, caching etc ...
- **Better integration with frameworks** ([Symfony](http://docs.php-http.org/en/latest/integrations/symfony-bundle.html) ATM, [Laravel](https://github.com/php-http/laravel-httplug) in progress): HTTPlug offer an integration to existing frameworks for library using this layer. In example, for Symfony all requests will be logged and traced when in dev mode (time, memory, diff at each modification, etc ....).
- **Shared work**: Many libraries already implement HTTPlug or are on the way, this mean, we can better profit for feature offered / wanted by other libraries.

And you get them all for free by just improving the your package design. Selecting HTTPlug over client X will comply with Dependency inversion principle.

**Comment by yukoff** [comment]
@Nyholm, @greg0ire -- first of all, thank you for your feedback! I'm perfectly aware of advs of HTTPlug abstraction, as well as aware of reasons not doing so 😉 I'll leave this one open for future consideretations.

**Comment by Nyholm** [comment]
Thank you for your answer. 
Do you mind share your reasons not to use HTTPlug? I do not know any good reason but "I do not want it" (which is,
btw, a perfectly fine reason)

**Comment by yukoff** [comment]
Don't get me wrong, I'm neither objecting against HTTPlug nor saying "I don't want it" 😉 I'm just said both (HTTPlg and guzzle) are PSR-7 compliant, so I don't see a big difference to replace one with another. Actually I like the idea, but it's not the kind of decision I should make on my own - let's see what @wtfzdotnet think on this matter when he'll get better.

Anyway thank you for your suggestions and feedback, they're much appreciated! 👍

**Comment by wtfzdotnet** [comment]
I think it is a valid idea, especially with the various options and versions of libraries out there ( which can be a pain in the ass to deal with ). However, I'd invite you guys to make a PR for this and I'll happily look at it ( I think @yukoff too :) ), I just don't have the time anymore to maintain this library constantly, let alone push forward the ideas I had for the next major version ( ditching a lot of code and let normalizers/serializers handle it ).

I can imagine in a situation where you have conflicting dependencies having this is extremely useful, but as @yukoff mentioned they should be compatible in most recent cases. Albeit it would require the end-user to rewrite some of the listeners to their preferred option, and it would be really nice to streamline this with one package.

**Comment by wtfzdotnet** [comment]
We are going all-in for psr implementations for `4.0` :-)
