### ISSUE TITLE
Your request count (46) is over the allowed limit of 40.

### ISSUE THREAD

**Issue by daverdalas** [php-tmdb/api#154]
Hey, I encountered such an error while using api:
 ```
Client error: GET https://api.themoviedb.org/3/search/tv?page=1&first_air_  
  date_year=2017&query=Orange%20Is%20the%20New%20Black&api_key=MY_API` resulted in a `429 Too Many Requests` response:          
  {"status_code":25,"status_message":"Your request count (46) is over the all  
  owed limit of 40."} 
```
I did an investigation and came to this conclusion. Request headers are now returend as arrays ex.
![image](https://user-images.githubusercontent.com/5399813/29967914-55a5474a-8f19-11e7-802f-c92b7e73fd0d.png)
I checked it on localhost and on the server. Both return headers in such a format. Maybe it was a change in Guzzle?
This can be easily fixed by changing:
`$sleep = (int) $response->getHeader('retry-after');`
to:
`$sleep = (int) $response->getHeader('retry-after')[0];`
in the file:
https://github.com/php-tmdb/api/blob/2.1/lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php#L79
I'm just curious if the problem occurs not only for me?
I'm using Guzzle version 6.3

**Comment by daverdalas** [comment]
Related: https://github.com/guzzle/guzzle/issues/1343 We should use getHeaderLine instead of getHeader

**Comment by yukoff** [comment]
@daverdalas The error you provided says you're doing a lot of requests and thir count is above allowed limit - it's a HTTP reply from server with 429 status code and proper status message `Your request count (46) is over the allowed limit of 40.` Just didn't get how you came to fixing `getHeader()`/`getHeaderLine()`? 😉

**Comment by yukoff** [comment]
I mean it's not clear how you came to conclusion from the error snippet provided. Most likely in addition to wrong `(int)` conversion (and in turn wrong wait times) you probably hit the max retries count (as seen [here](https://github.com/php-tmdb/api/blob/2.1/lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php#L64)), it was the only case I was able to reproduce, it failed on `$retries = 5`, eg.
* retries: 0, sleep: 1
* retries: 1, sleep: 0
* retries: 2, sleep: 0
* retries: 3, sleep: 0
* retries: 4, sleep: 0
On the next try you'll get error:
> Your request count (46) is over the allowed limit of 40.
