### ISSUE TITLE
no person popularity if loaded via peoplerepository

### ISSUE THREAD

**Issue by cyrus86** [php-tmdb/api#167]
the array i get via `$client->getPeopleApi()->getPerson()` holds a key for popularity whereas
```php
$pplRepo = new \Tmdb\Repository\PeopleRepository($client);
$rdm = $pplRepo->getLatest();
```
does not seem to have a `getPopularity()` method. Am I doing something wrong?

**Comment by wtfzdotnet** [comment]
This property was added since recent updates to the model, changes are reflected in the corresponding versions.
