### ISSUE TITLE
Parse error in setup

### ISSUE THREAD

**Issue by danmtslatter** [php-tmdb/api#168]
Hi There, 

After installing everything via composer and requiring relevant files, I'm getting a parse error: `Parse error: syntax error, unexpected ':', expecting ';' or '{' in /vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php on line 220`.

My code so far is absolutely vanilla:

		require_once '../vendor/autoload.php';
		require_once '../vendor/php-tmdb/api/apikey.php';

		$token  = new \Tmdb\ApiToken('xxx-xxx-xxx');
		$client = new \Tmdb\Client($token);

		$client = new \Tmdb\Client($token, [
		    'cache' => [
		        'path' => '/tmp/php-tmdb'
		    ]
		]);

		$person = $client->getPeopleApi()->getPerson(33);
		var_dump($person);
		exit;

As a relative novice, I'm not sure how to go about fixing this, any help greatly appreciated.

Thanks, Dan.

**Comment by danmtslatter** [comment]
Update: Problem appears to have disappeared switching environment to PHP 7 rather than 5.6.10, should this be the case?

**Comment by wtfzdotnet** [comment]
So sorry to come back so late with a decent reply, this completely depends on how you installed your dependencies, I am assuming you installed them with php7+, caught this while working with php5. And that makes perfect sense as the php7 version of doctrine cache uses specific features of php7+.
