### ISSUE TITLE
Genre getID says yes getName says no

### ISSUE THREAD

**Issue by frost-au** [php-tmdb/api#169]
I'm not sure exactly what I'm doing wrong. I've been trying to pull the name of genres for a group of movies but when I use getName() I get null values. If I change getName to getID I get integers back so I'm not sure what I'm doing wrong.

I also tried one of the examples inserted into my code and they return null as well.

Can anyone shead some light on what I'm doing wrong here?

**Comment by z38** [comment]
Thank you for your report. Can you share how you fetch the movies from the API and which example you tried running?

**Comment by frost-au** [comment]
I don't have the code any longer but I just tried to recreate it and had no issues with the genre name. I also had issues with cast and crew so I'll see if that works now. (probably is)

Probably just my noob self screwing up. I'm more familiar with the API now than when I started.

**Comment by wtfzdotnet** [comment]
If you need anymore help feel free to ask!
