### ISSUE TITLE
TV Episodes crew and guest stars not present

### ISSUE THREAD

**Issue by gbdematos** [php-tmdb/api#171]
If we do a normal API call to TMDB to get a season, all episodes information are present, including crew and guest stars. But if we do:

```
$season = $seasonRepository->load($tmdbId, $seasonNumber);
```

And then fetch an episode inside `$season`, `$episode->getCredits()` returns an empty CreditsCollection! Where did the info go?!

**Comment by wtfzdotnet** [comment]
Closing this, a fix is going to be releaed in 2.1.15 tonight. Thanks to @z38
