### ISSUE TITLE
trailers and embedding

### ISSUE THREAD

**Issue by frost-au** [php-tmdb/api#176]
Hi,

Maybe its my ignorance of how the API works but when I grab the trailer URL from the API it gives me a link to the trailer which is fine, but if you want to embed it on your site this is useless. I've ended up grabbing the key and building my own URL with /embed/ but I guess I'm asking is there any way to do this out of the box or get this added? only minor inconvenience after all. 

Thanks

**Comment by aliem3x** [comment]
Hi, 

go to: \vendor\php-tmdb\api\lib\Tmdb\Model\Common\Video\Youtube.php
and change the URL_FORMAT to

`const URL_FORMAT = 'http://www.youtube.com/embed/%s';`

Dont forget the %s because it's replaced by the video code.

**Comment by wtfzdotnet** [comment]
I guess you are talking about the `Youtube` class, which you can call `getSource()` on which contains the id, if you would expect something else of the library then please do elaborate.
