### ISSUE TITLE
Giving Different Release Date Compared to TMDB developers.themoviedb.org  

### ISSUE THREAD

**Issue by limuel567** [php-tmdb/api#187]
This is the screenshot of data using your wrapper:
![screenshot_7](https://user-images.githubusercontent.com/40750374/46012537-2d5a8a00-c0fc-11e8-8d4d-f91c14d86c58.jpg)
And This is the screenshot of data from the developers.themoviedb.org
![screenshot_6](https://user-images.githubusercontent.com/40750374/46012553-39dee280-c0fc-11e8-8e22-323a099e6b7c.jpg)

And the problem here is that, they have different release date can you explain why and what do i need to do to fix this?

**Comment by wtfzdotnet** [comment]
Spent a little time digging into this, but I am not sure why your screenshot result of that page gives a way different date than the actual results ( and what is actually displayed at tmdb https://www.themoviedb.org/movie/365371-war-stories-our-mother-never-told-us )

**Comment by wtfzdotnet** [comment]
@limuel567 can you possibly provide a bit more information where exactly I should be looking for this behavior to occur?
