### ISSUE TITLE
TheMovieDB certificate expired

### ISSUE THREAD

**Issue by DariusIII** [php-tmdb/api#190]
Today their certificate expired and causing configuration through curl to fail. 

 ```
Tmdb \ Exception \ NullResponseException
The request to path "configuration" with query parameters "{"api_key":"xxxxxxxxxxxxx"}" failed to return a valid response. The previous exception reported "cURL error 60: SSL certificate problem: certificate has expired (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)" at "/var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186".
```

Can it be bypassed somehow before the site fixes their certificate?

**Comment by wtfzdotnet** [comment]
Hi Darius, im currently in the train, so I'm going to be prompt, there are
instructions in the readme!

**Comment by DariusIII** [comment]
They fixed their certs shortly after i opened the issue.  Btw, readme does not cover themoviedb site ssl certificate expiration. There is an option to configure secure connection, but that is a whole different thing :)

Anyway my issue is solved now, so i am closing it.

P.S.; Thank you for your package, it is a valuable thing to have.
