### ISSUE TITLE
3rd Party Authentication Request Granted

### ISSUE THREAD

**Issue by lilpkstud** [php-tmdb/api#191]
Having trouble redirecting back to my website after user to granted permission to my app.

**Comment by wtfzdotnet** [comment]
@lilpkstud sorry for the late reply, but I hope you can understand nobody here on the other end can wave a magic wand and fix it based on the information you have provided. Closing this issue as it seems to be an user-space problem and not so much with the library itself, if there however is an actual issue within the library please do open a new issue and provide as much details as possible.
