### ISSUE TITLE
getList not returning any Tv Shows

### ISSUE THREAD

**Issue by lilpkstud** [php-tmdb/api#198]
I created a list of tv shows but the JSON result I get is empty for ["items"] while ["item_count"] have the correct number

`$list->getList(110918)`

JSON Result
`array(9) { ["created_by"]=> string(9) "lilpkstud" ["description"]=> string(10) "My KDramas" ["favorite_count"]=> int(0) ["id"]=> string(6) "110918" ["items"]=> array(0) { } ["item_count"]=> int(26) ["iso_639_1"]=> string(2) "en" ["name"]=> string(13) "Korean Dramas" ["poster_path"]=> NULL }`

**Comment by wtfzdotnet** [comment]
Tried to reproduce on `4.0`, without as far as I recall making any changes to this section, this works;

```php
<?php

/**
 * This file is part of the Tmdb PHP API created by Michael Roterman.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package Tmdb
 * @author Michael Roterman <michael@wtfz.net>
 * @copyright (c) 2013, Michael Roterman
 * @version 4.0.0
 */

require_once '../../../vendor/autoload.php';
require_once '../../apikey.php';

/** @var Tmdb\Client $client * */
$client = require_once('../../setup-client.php');
$client->getEventDispatcher()->addListener(
    \Tmdb\Event\BeforeRequestEvent::class,
    new Tmdb\Event\Listener\Request\SessionTokenRequestListener(
        new \Tmdb\Token\Session\SessionToken(TMDB_SESSION_TOKEN)
    )
);

$list = $client->getListsApi()->getList(LIST_ID);

var_dump($list);
```

Closing for now if issue persists please re-open and provide an example.
