### ISSUE TITLE
api-2.1.17 package has a broken phpunit symlink

### ISSUE THREAD

**Issue by lachlan-00** [php-tmdb/api#199]
Just an fyi relating to this issue that was opened
https://github.com/ampache/ampache/issues/2205#event-2831190841

**Comment by wtfzdotnet** [comment]
As far as I am concerned, when upgraded from 2.0 towards 4.0 this symlink does not exist anymore, upgrading to 4.0 with recent php versions should be a small effort. Sorry for the long wait but I haven't given this baby much attention the past years :-).
