### ISSUE TITLE
Missing Region Plugin OR No way to set region globally 

### ISSUE THREAD

**Issue by angelxmoreno** [php-tmdb/api#200]
It seems like unless I set a region to various endpoints, the movies that come back are not what is expected. This is especially true with the Upcoming Movies endpoint as stated in this thread:
https://www.themoviedb.org/talk/5cd42dde0e0a265e06610495

Are there plans to assign a region globally via plugin or some other way?

**Comment by angelxmoreno** [comment]
I don't mind submitting a PR if the authors warrant this plugin as useful

**Comment by wtfzdotnet** [comment]
Will be included in `4.0` as the `RegionFilterRequestListener`.
