### ISSUE TITLE
Can't install from composer, conflict with version of symfony/event-dispatcher

### ISSUE THREAD

**Issue by hijoem** [php-tmdb/api#202]
Hi. Sorry for my bad English.

I'm interested using this wrapper in my project.
I'm using Lumen https://lumen.laravel.com and it got conflicted.

I only know a little about composer.
So I tried `composer require php-tmdb/api` 
( I tried this too `composer require php-tmdb/api ~2.1` )
then I got a veery loong errors and here is a part of it :
```
- symfony/event-dispatcher` v4.3.9 conflicts with symfony/console[v5.0.6].
- Installation request for symfony/console (locked at v5.0.6) -> satisfiable by symfony/console[v5.0.6].
- Installation request for php-tmdb/api ~2.1 -> satisfiable by php-tmdb/api[2.1.0, 2.1.16, 2.1.17, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.x-dev, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.14, v2.1.15, v2.1.9].
```
Then I compare your composer.json
```
        "symfony/event-dispatcher": ">=2.4,<5",
        "symfony/options-resolver": ">=2.6,<5",
```
with Lumen's
```
        "symfony/console": "^5.0",
        "symfony/error-handler": "^5.0",
        "symfony/http-kernel": "^5.0",
        "symfony/http-foundation": "^5.0",
        "symfony/mime": "^5.0",
        "symfony/var-dumper": "^5.0",
```
and there, the version is the problem.

Is there any way for me using this wrapper?
Thank you so much.

**Comment by wtfzdotnet** [comment]
You should try and move to the new 3.0 release, that was recently contributed :-)

**Comment by hijoem** [comment]
ah, right,,
I'll try it then.

kindly thank you for your reply.
