### ISSUE TITLE
Supply some helper methods in the client to obtain extra Rate Limit information.

### ISSUE THREAD

**Issue by wtfzdotnet** [php-tmdb/api#21]
Every request will soon have these 3 headers:

X-RateLimit-Limit: 30
X-RateLimit-Remaining: 18
X-RateLimit-Reset: 1394060670

Helpers to obtain these headers should be available in `Tmdb/Client`.

**Comment by Rtransat** [comment]
Sorry to reopen this issue, but why in the [Tmdb\Client](https://github.com/php-tmdb/api/blob/2.0/lib/Tmdb/Client.php) this commit 249855eb900d1def68694b60dcf25f77095c970e is not present ? I need to get information about rate limit.

For example I use the discover repository:

```$this->repository->getClient()->``` but in Tmdb\Client the following methods are not present:
getRateLimitFromLastResponse
getRateLimitRemainingFromLastResponse
getRateLimitResetFromLastResponse

I can do that:
```php
$data = $this->repository->discoverTv($query);
dd($this->repository->getClient()->getHttpClient()->getLastResponse()->getHeaders()); // all headers are returned
```

but with that:
```php
$data = $this->repository->discoverTv($query);
dd($this->repository->getClient()->getHttpClient()->getLastResponse()->getHeader('X-RateLimit-Remaining")); // Call to undefined method Tmdb\HttpClient\Response::getHeader()
```

**Comment by wtfzdotnet** [comment]
I'll look into this tomorrow with some other maintenance duties, I hope you can understand I can't remember the exact details right now about a commit from 1.5 years ago :-)

Are you running the latest version? ( I'd assume you are but just in case ... ) If not what version are you on?

**Comment by Rtransat** [comment]
I undertand, don't worry :).
Yes I use the last version (I use the wrapper with the laravel package)

**Comment by wtfzdotnet** [comment]
@Rtransat the branch you are referring to never got merged, as this was an implementation with a different background of dependency versions. ( Took TMDB a long time to actually implement the RFC ).

In the `Response` object there is no `getHeader` method currently, however calling `getHeaders()->get('X-Header')` should do the job.
