### ISSUE TITLE
How to Get Movies/TV List with Only "Original Language"

### ISSUE THREAD

**Issue by anandtechmedia** [php-tmdb/api#211]
Hi,

How do we get the Movies/TV Lists with only "Original Language" and not in English. Eg., We want all the movies related to Telugu, Tamil, Malayalam & Kannada to be displayed. How to query that?

This is the API from TMDB to get Movie List related to Telugu language,
https://api.themoviedb.org/3/discover/movie?api_key=###&with_original_language=te&year=2019

Kindly advise on how to get the desired list as mentioned above.

Thanking you,

Best Regards,
Saran

**Comment by wtfzdotnet** [comment]
I am afraid you really have to consult the documentation of themoviedb for this.
