### ISSUE TITLE
Episode Group missing?

### ISSUE THREAD

**Issue by sheriffmarley** [php-tmdb/api#228]
Tmdb introduced a while ago the `episode_group` feature where you can get other episode grouping for seasons.

Best example I could found was La casa de papel  https://www.themoviedb.org/tv/71446-la-casa-de-papel/episode_groups  

 Is this functionality currently missing, or did I just wasn't able to find?

**Comment by wtfzdotnet** [comment]
@sheriffmarley took a little break from the project after the recent large update; 

This feature is not implemented, we can put it on the the list for things to be added in the future. Could you possibly provide a pr with this feature?
