### ISSUE TITLE
need help  

### ISSUE THREAD

**Issue by AMWolfstein** [php-tmdb/api#231]
Hello dev , 

  I know that maybe this php files is not yours  but I hope that you will help  me fixing this issue . I have issue while importing season episodes for the newest tv series like " lupin " . there is no importing for episodes  on this script .  I tried to know  what is the bug here and found that if the series has 0 season or Specials season , the importing  working fine . if there is no  0 season or Specials season , here  is the bug .always  season 1  importing 0 episodes , season 2  importing season 1 episodes and season 3 importing season 2 episodes ...etc .

I made the script in this zip file . I hope you can help me
[Desktop.zip](https://github.com/php-tmdb/api/files/5862207/Desktop.zip)

**Comment by wtfzdotnet** [comment]
I took a quick peek but this is not even using our library, you might want to give our [symfony bundle](https://github.com/php-tmdb/symfony) a try :-).
