### ISSUE TITLE
RequestQueryHelper unexpectedly converts dots/periods in parameters to underscores

### ISSUE THREAD

**Issue by neildaniels** [php-tmdb/api#236]
I was trying to do a a TV discovery request with `air_date.gte` and `air_date.lte` and was getting unexpected results.

Enabled logging and discovered that after `ApiTokenRequestListener` appending the API token (v3 query parameter style) the parameters that had a period had been converted to underscores (e.g. `air_date_gte` and `air_date_lte`) and the server was not understanding those parameters.

Specifically, `RequestQueryHelper` uses `parse_str()` which [converts periods to underscores](https://www.php.net/manual/en/function.parse-str.php). 
https://github.com/php-tmdb/api/blob/0980c7d9a41da387205d9e4affb16d776706d5c6/lib/Tmdb/Helper/RequestQueryHelper.php#L41-L51

**Comment by wtfzdotnet** [comment]
Was never aware `parse_str` has this quirky behavior up till now; something learned. I don't really like the sight of the resolution brought up with #237... But after tinkering with it a bit quickly I understand given the circumstances of the `UriInterface` we don't have much to go with. 

Need to give this a little more thought, will get back asap.

**Comment by wtfzdotnet** [comment]
@neildaniels going to be very honest with you; still haven't come up with a solution to this that satisfies me; leaning towards your proposal a.t.m. since php seems to be just be buggy in this regard...
