### ISSUE TITLE
General API Usage - Undefined "api_token" on Client() construction

### ISSUE THREAD

**Issue by mattkloc** [php-tmdb/api#239]
Hi everyone, I am attempting to integrate the new 4.0 version of the **php-tmdb/api** project within my existing web app however ran into the following error below.

Is anyone aware of what steps I may be missing? I took a look at the existing example files, but I'm not sure beyond the examples the order of operations to get the basic API usage working even though I managed to install all the dependencies without any issues.

I've tried creating a duplicate of the **apikey.php** file from the examples folder and referencing it within the Database.php model that calls the code below but without any luck.

Code
```
use Tmdb\Client;

$client = new Client();
$movie = $client->getMoviesApi()->getMovie(550);
```

Error
```
  ErrorException

  Undefined array key "api_token"

  at vendor/php-tmdb/api/lib/Tmdb/Client.php:175
    171▕                 'null'
    172▕             ]
    173▕         );
    174▕
  ➜ 175▕         if (is_string($options['api_token'])) {
    176▕             $options['api_token'] = new ApiToken($options['api_token']);
    177▕         }
    178▕
    179▕         $this->options = $this->postResolve(

      +2 vendor frames
  3   app/Models/Database.php:93
      Tmdb\Client::__construct()

  4   app/Console/Commands/UpdateMovies.php:48
      App\Models\Database::getTmdbMovies()
```

**Comment by mattkloc** [comment]
After further inspection I was able to better follow the examples provided and got the basic API usage working

**Comment by souareba** [comment]
Hello, i'd like to know how did you solve the problem ?
I unfortunately have the same issue
