### ISSUE TITLE
[bug] Episode AirDate has wrong value when TMDB api returns empty

### ISSUE THREAD

**Issue by ptheofan** [php-tmdb/api#242]
```php
$season = $repo->load(71712, 5);  // The good doctor, current season
$episodes = $season->getEpisodes();
$episodes[5]->getAirDate(); // should be null, atm episodes 6-10 have no air-date

// currently the return value is a DateTime of 2021-09-21 19:31:17.648338 (which is the actual UTC time at the moment the code was run)
```

Here's the actual response from the TMDB Api
![Actual Response from TMDB API](https://user-images.githubusercontent.com/880939/134236647-57a1c51d-07ed-4863-868e-7873dd7bd86d.png)

After doing some digging the problem is here (TMDB Api return empty string, but the inflator checks for null)
![image](https://user-images.githubusercontent.com/880939/134238453-68d403c6-a02e-461f-9219-346fc915c516.png)

https://github.com/php-tmdb/api/blob/e330e8f9c74187dc47fdff2cd5b4acef1ffae096/lib/Tmdb/Model/Tv/Episode.php#L167

**Comment by ptheofan** [comment]
Related Pull Request #243

**Comment by wtfzdotnet** [comment]
Thanks for this :-)
