### ISSUE TITLE
Undefined array key "api_token" in /html/vendor/php-tmdb/api/lib/Tmdb/Client.php on line 175

### ISSUE THREAD

**Issue by Yupy** [php-tmdb/api#265]
I installed all dependencies, added the API key to examples/apikey.php loaded the file into my php page and get this error:

Undefined array key "api_token" in /html/vendor/php-tmdb/api/lib/Tmdb/Client.php on line 175

It only works when I use the examples with var_dump but not with for example:

`use Tmdb\Repository\MovieRepository;
use Tmdb\Client;

$client = new Client();
$repository = new MovieRepository($client);
$movie = $repository->load(87421);

echo $movie->getTitle();`

**Comment by Yupy** [comment]
Managed to make it work.

**Comment by McAtze** [comment]
I have the same error, what was your Solution?
