### ISSUE TITLE
[ON-HOLD] Implement RFC6585 Section-4 for Rate Limiting

### ISSUE THREAD

**Issue by wtfzdotnet** [php-tmdb/api#62]
This was already implemented in an old pull request, and this pull request pretty much went forgotten about. Got word from the TMDB developer that this might be implemented soon after all.

I hope this can still be included for 2.0, awaiting news from the topic here: http://tmdb.lighthouseapp.com/projects/83077/tickets/356-implement-rfc6585-section-4-for-rate-limiting

**Comment by arohter** [comment]
Is now live !

```
$ curl -sD -  http://api.themoviedb.org/3/ | grep Rate
X-RateLimit-Limit: 40
X-RateLimit-Remaining: 37
X-RateLimit-Reset: 1432089148
```

**Comment by wtfzdotnet** [comment]
Took a while haha, I'm a little bit preoccupied currently but I'll try to get through the current issues by this weekend.

**Comment by wtfzdotnet** [comment]
https://github.com/php-tmdb/api/pull/88 incoming
