### ISSUE TITLE
TV-Api Implement alternative Titles

### ISSUE THREAD

**Issue by riyuk** [php-tmdb/api#85]
Would be useful to add a Tmdb::getTvApi()->getAlternativeTitles($id) - Method

- http://docs.themoviedb.apiary.io/#reference/tv/tvidalternativetitles

Thanks in advanced

**Comment by wtfzdotnet** [comment]
Sorry for the late reply, still actively maintaining just preoccupied lately, I'll see what I can do this weekend!

**Comment by wtfzdotnet** [comment]
PR #89 solves this, will merge it in soon after Travis is satisfied.

**Comment by wtfzdotnet** [comment]
Update to `2.0.8`.
