### ISSUE TITLE
OptionsResolver throwing exception with composer update

### ISSUE THREAD

**Issue by dptoot** [php-tmdb/api#86]
Looks like the package is requiring ~2.1 but a composer update will give me v2.6+ now.  With it comes an exception:

ErrorException: Calling the Symfony\Component\OptionsResolver\OptionsResolver::setAllowedTypes method with an array of options is deprecated since version 2.6 and will be removed in 3.0. Use the new signature with a single option instead.

**Comment by mighty-code** [comment]
Here same problem, I'd change my composer.json like the following:
```
"require": {
    "symfony/options-resolver":"2.1.*"
  },
```
This works for me till this is fixed.

**Comment by dptoot** [comment]
Thanks for the quick response!  

That is what I ended up doing but just wanted to give a heads up to the powers that be :)

**Comment by Ugoku** [comment]
+1

Thanks for the hotfix mighty-code!

**Comment by mighty-code** [comment]
no problem ;)

**Comment by wtfzdotnet** [comment]
Merged https://github.com/php-tmdb/api/pull/81
