### ISSUE TITLE
Unrecognized media_type "episode"

### ISSUE THREAD

**Issue by koichirose** [php-tmdb/api#87]
I'm having this exception thrown here:
RuntimeException in ImageFactory.php line 90:
Unrecognized media_type "episode" for method "Tmdb\Factory\ImageFactory::Tmdb\Factory\ImageFactory::createMediaImage".

https://github.com/php-tmdb/api/blob/2.0/lib/Tmdb/Factory/ImageFactory.php#L91

My code:
```
		$token  = new \Tmdb\ApiToken($tmdb_api_key));
		$client = new \Tmdb\Client($token);
		$repository = new \Tmdb\Repository\PeopleRepository($client);
		$tmdb_id = 17051; // James Franco
		$tmdb_person = $repository->load($tmdb_id);

```

I guess episode images are not supported, is there a way around this, other than catching a generic RuntimeException?

Thanks

**Comment by wtfzdotnet** [comment]
There's an couple of issues I still have to address, I hope to have time this Sunday, could you for now just catch it, I'll see what I can do asap.

**Comment by okaufmann** [comment]
Is there something new in this error? I have the same Issue...
