### ISSUE TITLE
Cache Config Error

### ISSUE THREAD

**Issue by johannesx75** [php-tmdb/api#99]
I was trying to switch from filesystem cache to ArrayCache 
```php
new \Tmdb\Client($token, [ 
'cache' => [
	'enabled' => false,
	'storage' => new \Doctrine\Common\Cache\ArrayCache()
	]
]);
```

It gives me an error:
> ERROR [User Error]: Uncaught Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The option "storage" does not exist. Defined options are: "enabled", "handler", "path", "subscriber".

Am I missing some library?
Thanks

**Comment by DeeJaVu** [comment]
same issue here

**Comment by wtfzdotnet** [comment]
Hi guys, I'll try and look at this ASAP, I just got back from a weekend in Brussels.

**Comment by wtfzdotnet** [comment]
@johannesx75 Looking at this now, however I'd strongly recommend against switching to the array cache because of the rate limits, what is your use-case?

**Comment by wtfzdotnet** [comment]
@johannesx75 I'll assume your making use of symfony for simplicity sake, please see my comment: https://github.com/php-tmdb/symfony/issues/8#issuecomment-113961962

**Comment by johannesx75** [comment]
We keep a lokal copy of tmdb. When reinit that copy the filesystem-cache kills the filesystem. It creates so many directories and files under /tmp that we run out of inodes on the filesystem. We have enough space, just not enough inodes. :(

We don't use symfony. We use SilverStripe as a CMS and Framework and then your wrapper to import / update from tmdb. For now I disabled the cache completely. Seems to work, but I guess some form of cacheing wouldn't hurt.

**Comment by wtfzdotnet** [comment]
@johannesx75 I'd suggest moving over to Redis or Memcached, throw them into memory instead :). Putting filesystem as a default never had my preference, but caching as a default enabled still seems to make the most sense. Just fixed a related bug to passing the `['cache' => ['enabled' => false ]]` option.

**Comment by johannesx75** [comment]
Yeah I didn't want to setup and maintain jet another system like Redis. But we keep running into places where Redis could be useful (cache, session storage, ...).
I'll talk to our admin and see what can be done.

Thanks for the input!

**Comment by johannesx75** [comment]
But I guess the cache documentation is still wrong, or am I missing something?
(don't need it right now. just want to help other running into the problem)

**Comment by wtfzdotnet** [comment]
I see the section now, I'll adjust it

**Comment by johannesx75** [comment]
thank! you rock!

**Comment by wtfzdotnet** [comment]
@johannesx75 Just updated it, sorry for the wait :)
